services:
  - type: web
    name: token-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: token-db
          property: connectionString

databases:
  - name: token-db
    databaseName: tokens
    user: tokens_user